### ISSUE TITLE
vb.net using parameters?

### ISSUE THREAD

**Issue by klmcsa** [gqy117/XpdfNet#16]
using in vb.net after using nuget to install:
Imports XpdfNet
        Dim pdfHelper As XpdfHelper = New XpdfHelper()
        Dim intext As String = pdfHelper.ToText("C:\pdftest.pdf")

I can find no way to enter parameters like -lineprinter that the command line xpdftotext.exe will take.  Is there anyway to do the same as:

xpdftotext.exe -lineprinter "c:\pdftest.pdf"

**Comment by gqy117** [comment]
Hi @klmcsa, thank you for reporting that.

I've pushed **1.2.0** version. 

Which has the capability of using arguments

`Dim intext As String = pdfHelper.ToText("C:\pdftest.pdf", "−lineprinter")`

Or other arguments

`Dim intext As String = pdfHelper.ToText("C:\pdftest.pdf", "-eol unix −lineprinter")`

Let me know if it suits your use case. 😃

**Comment by klmcsa** [comment]
Works Great Thank You!!!!

equivalent of: xpdftotext.exe -lineprinter "c:\pdftest.pdf"

Visual basic:

        Dim pdfHelper As XpdfHelper = New XpdfHelper()
        Dim intext As String = pdfHelper.ToText("C:\pdftest.pdf", "−lineprinter")
        If System.IO.File.Exists("C:\workfileoutput.txt") = True Then
            System.IO.File.Delete("C:\workfileoutput.txt")
        End If
        Dim file = My.Computer.FileSystem.OpenTextFileWriter("C:\workfileoutput.txt", True)
        file.WriteLine(intext)
        file.Close()
