### ISSUE TITLE
Error Installing Version 1.0.7 From NuGet

### ISSUE THREAD

**Issue by addisonbgross** [gqy117/XpdfNet#4]
Having this error whenever I attempt to install the latest version

`
Error downloading 'XpdfNet.1.0.7' from 'https://api.nuget.org/v3flatcontainer/xpdfnet/1.0.7/xpdfnet.1.0.7.nupkg'.
Access to the path 'C:\Users\<user name>\.nuget\packages\xpdfnet\1.0.7\build' is denied.
`

However 1.0.6 does install correctly

**Comment by gqy117** [comment]
Thank you for reporting this issue, @addisonbgross :)
I've fixed it and pushed version 1.0.10
